package com.devel.views.menus;

import com.devel.custom.DnDTabbedPane;
import com.devel.utilities.Propiedades;
import com.devel.utilities.Utilidades;
import com.devel.views.tabs.VAlumnos;
import com.devel.views.tabs.VMatricula;
import com.devel.views.tabs.VWelcome;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Locale;


public class MenuInicio {
    private JButton inicioButton;
    private JPanel panelPrincipal;
    private JButton matriculaButton;
    private DnDTabbedPane tabContenido;
    private VWelcome welcome;
    private VAlumnos alumnos;
    private VMatricula matricula;
    private Propiedades propiedades;

    public MenuInicio(final DnDTabbedPane tabContenido) {
        this.tabContenido = tabContenido;
        inicioButton.addActionListener(e -> {
            cargarBienvenida();
            matriculaButton.setBackground(new JButton().getBackground());
            Utilidades.buttonSelectedOrEntered(inicioButton);
        });
        matriculaButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                cargarMatricula();
                inicioButton.setBackground(new JButton().getBackground());
                Utilidades.buttonSelectedOrEntered(matriculaButton);
            }
        });
    }

    public JPanel traerInicioOpciones() {
        return panelPrincipal;
    }

    public void cargarBienvenida() {
        if (welcome == null) {
            welcome = new VWelcome();
        }
        if (tabContenido.indexOfComponent(welcome.getPanelPrincipal()) == -1) {
            welcome = new VWelcome();
            welcome.getPanelPrincipal().setOption(inicioButton);
            tabContenido.addTab(welcome.getTitle(), welcome.getPanelPrincipal().getIcon(), welcome.getPanelPrincipal());
        }
        tabContenido.setSelectedComponent(welcome.getPanelPrincipal());
        inicioButton.requestFocus();
    }

    public void cargarMatricula() {
        if (matricula == null) {
            matricula = new VMatricula();
        }
        if (tabContenido.indexOfComponent(matricula.getPanelPrincipal()) == -1) {
            matricula = new VMatricula();
            matricula.getPanelPrincipal().setOption(matriculaButton);
            tabContenido.addTab(matricula.getTitle(), matricula.getPanelPrincipal().getIcon(), matricula.getPanelPrincipal());

        }
        tabContenido.setSelectedComponent(matricula.getPanelPrincipal());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelPrincipal = new JPanel();
        panelPrincipal.setLayout(new GridLayoutManager(3, 1, new Insets(0, 5, 5, 5), -1, 10));
        panelPrincipal.setMaximumSize(new Dimension(140, 2147483647));
        panelPrincipal.setMinimumSize(new Dimension(140, 164));
        panelPrincipal.setPreferredSize(new Dimension(140, 164));
        inicioButton = new JButton();
        inicioButton.setFocusPainted(false);
        Font inicioButtonFont = this.$$$getFont$$$(null, -1, 14, inicioButton.getFont());
        if (inicioButtonFont != null) inicioButton.setFont(inicioButtonFont);
        inicioButton.setSelected(false);
        inicioButton.setText("Inicio");
        panelPrincipal.add(inicioButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panelPrincipal.add(spacer1, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        matriculaButton = new JButton();
        matriculaButton.setFocusPainted(false);
        Font matriculaButtonFont = this.$$$getFont$$$(null, -1, 14, matriculaButton.getFont());
        if (matriculaButtonFont != null) matriculaButton.setFont(matriculaButtonFont);
        matriculaButton.setText("Matricula");
        panelPrincipal.add(matriculaButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelPrincipal;
    }
}
