package com.devel.views.dialogs;

import com.devel.utilities.Colors;
import com.devel.utilities.JButoonEditors.JButtonEditorSeguros;
import com.devel.utilities.JButoonEditors.JTableButtonRenderer;
import com.devel.utilities.TablecellRendered.SegurosCellRendered;
import com.devel.utilities.TablecellRendered.SegurosPersonasCellRendered;
import com.devel.utilities.Utilidades;
import com.devel.utilities.modelosTablas.SegurosAbstractModel;
import com.devel.views.VPrincipal;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.table.TableCellRenderer;
import java.awt.*;
import java.awt.event.*;

public class DGestionarSeguros extends JDialog {
    private JTable tablaSeguros;
    private JButton btnAñadir;
    private JButton btnHecho;
    private JPanel panelPrincipal;
    private SegurosAbstractModel segurosAbstractModel;

    public DGestionarSeguros() {
        iniciarComponentes();
        btnAñadir.addActionListener(e -> {
            cargarCrearSeguro();
        });
        btnHecho.addActionListener(e -> {
            cerrar();
        });
        panelPrincipal.registerKeyboardAction(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                cerrar();
            }
        }, KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
    }

    private void iniciarComponentes() {
        setTitle("Seguros");
        setContentPane(panelPrincipal);
        cargarTabla();
        pack();
        setLocationRelativeTo(null);
        setResizable(false);
        setModal(true);
        getRootPane().setDefaultButton(btnAñadir);
    }

    private void cargarCrearSeguro() {
        DAñadirSeguro dAñadirSeguro = new DAñadirSeguro();
        dAñadirSeguro.setVisible(true);
        Utilidades.actualizarTabla(tablaSeguros);
    }

    private void cargarTabla() {
        segurosAbstractModel = new SegurosAbstractModel(VPrincipal.seguros);
        tablaSeguros.setModel(segurosAbstractModel);
        tablaSeguros.getColumnModel().getColumn(segurosAbstractModel.getColumnCount() - 1).setCellEditor(new JButtonEditorSeguros(tablaSeguros));
        TableCellRenderer renderer1 = tablaSeguros.getDefaultRenderer(JButton.class);
        tablaSeguros.setDefaultRenderer(JButton.class, new JTableButtonRenderer(renderer1));
        Utilidades.definirTamaño(tablaSeguros.getColumn(""), 30);
        SegurosPersonasCellRendered.setCellRenderer(tablaSeguros);
        SegurosCellRendered.setCellRenderer(tablaSeguros);
    }

    private void cerrar() {
        dispose();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelPrincipal = new JPanel();
        panelPrincipal.setLayout(new GridLayoutManager(2, 3, new Insets(10, 10, 10, 10), -1, 10));
        btnHecho = new JButton();
        btnHecho.setText("Hecho");
        panelPrincipal.add(btnHecho, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        panelPrincipal.add(scrollPane1, new GridConstraints(0, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        tablaSeguros = new JTable();
        tablaSeguros.setRowHeight(25);
        scrollPane1.setViewportView(tablaSeguros);
        btnAñadir = new JButton();
        btnAñadir.setText("Nuevo");
        panelPrincipal.add(btnAñadir, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panelPrincipal.add(spacer1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelPrincipal;
    }
}
