package com.devel.views.dialogs;

import com.devel.models.Grado;
import com.devel.utilities.Colors;
import com.devel.utilities.JButoonEditors.JButtonEditorGrados;
import com.devel.utilities.JButoonEditors.JTableButtonRenderer;
import com.devel.utilities.TablecellRendered.GradoCellRendered;
import com.devel.utilities.Utilidades;
import com.devel.utilities.modelosTablas.GradoAbstractModel;
import com.devel.views.VPrincipal;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.table.TableCellRenderer;
import java.awt.*;
import java.awt.event.*;
import java.util.Vector;

public class DGestionarGrados extends JDialog {
    private JTable tablaGrados;
    private JButton btnAñadir;
    private JButton btnHecho;
    private JPanel panelPrincipal;
    private Grado grado;
    private GradoAbstractModel gradoAbstractModel;

    public DGestionarGrados() {
        iniciarComponentes();
        btnAñadir.addActionListener(e -> {
            cargarNuevoGrado();
        });
        btnHecho.addActionListener(e -> {
            cerrar();
        });
        panelPrincipal.registerKeyboardAction(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                cerrar();
            }
        }, KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
    }

    private void iniciarComponentes() {
        setTitle("Grados");
        setContentPane(panelPrincipal);
        cargarTabla();
        pack();
        setLocationRelativeTo(null);
        setModal(true);
        setResizable(false);
        getRootPane().setDefaultButton(btnAñadir);
    }

    private void cargarNuevoGrado() {
        DCrearGrado dCrearGrado = new DCrearGrado();
        dCrearGrado.setVisible(true);
        Utilidades.actualizarTabla(tablaGrados);
    }

    private void cargarTabla() {
        gradoAbstractModel = new GradoAbstractModel(VPrincipal.grados);
        tablaGrados.setModel(gradoAbstractModel);
        tablaGrados.getColumnModel().getColumn(gradoAbstractModel.getColumnCount() - 1).setCellEditor(new JButtonEditorGrados(tablaGrados));
        TableCellRenderer renderer1 = tablaGrados.getDefaultRenderer(JButton.class);
        tablaGrados.setDefaultRenderer(JButton.class, new JTableButtonRenderer(renderer1));
        Utilidades.headerNegrita(tablaGrados);
        GradoCellRendered.setCellRenderer(tablaGrados);
    }

    private void cerrar() {
        dispose();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelPrincipal = new JPanel();
        panelPrincipal.setLayout(new GridLayoutManager(2, 3, new Insets(10, 10, 10, 10), -1, 10));
        final Spacer spacer1 = new Spacer();
        panelPrincipal.add(spacer1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        panelPrincipal.add(scrollPane1, new GridConstraints(0, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        tablaGrados = new JTable();
        tablaGrados.setAutoCreateColumnsFromModel(true);
        tablaGrados.setAutoCreateRowSorter(false);
        tablaGrados.setRowHeight(25);
        scrollPane1.setViewportView(tablaGrados);
        btnAñadir = new JButton();
        btnAñadir.setText("Nuevo");
        panelPrincipal.add(btnAñadir, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnHecho = new JButton();
        btnHecho.setText("Hecho");
        panelPrincipal.add(btnHecho, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelPrincipal;
    }
}
